bootstrap.servers=15.135.1.142:9092,15.135.253.132:9092,13.237.136.252:9092
key.serializer=org.apache.kafka.common.serialization.StringSerializer
value.serializer=org.apache.kafka.common.serialization.StringSerializer

security.protocol=SASL_PLAINTEXT
sasl.mechanism=SCRAM-SHA-256
sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="ickafka" password="63aedb12e6851d88a695a285e89d08a2a0a731511b833ca43d726f26c5bf0a70";

max.block.ms=5000
request.timeout.ms=3000
